#!/usr/bin/env bash

# To use this file, run `source activate` and `helpme` to view usage.

function helpme {
  cat <<HELP_USAGE
  Production:
    dc [options] => docker-compose [options]
    dcup => Starts a Docker container in detached mode
    dcdown => Destroys the started Docker container
    dcrestart => Destroys and creates a new Docker container
    dcx <subsystem> [command] => docker-compose exec <subsystem> [command]
    
  setversion <version number> => Sets the VERSION_TAG environment variable
  setlatest => Sets the VERSION_TAG environment variable to the latest version available on GitHub
  
  The setlatest command requires curl and python to be installed.

  Development:
    dcd [options] => docker-compose -f docker-compose.dev.yml [options]
    dcdup => Builds the development Docker container using the docker-compose.dev.yml file
    dcddown => Destroys the development Docker container
    dcdrestart => Destroys and builds a new development Docker container
    dcdx <subsystem> [command] => docker-compose -f docker-compose.dev.yml exec <subsystem> [command]
    dcdsetup => Runs the setup commands within the development Docker container
HELP_USAGE
}

function is_shipper_version_tag_set {
  if [ -z "$VERSION_TAG" ]; then
    echo "Error: the version tag is not set. Stopping..."
    return 1
  fi
  return 0
}

function dc {
  if is_shipper_version_tag_set; then
    docker-compose "$@"
  fi 
}

function dcup {
  if is_shipper_version_tag_set; then
    docker-compose up -d "$@"
  fi  
}

function dcdown {
  if is_shipper_version_tag_set; then
    docker-compose down "$@"
  fi 
}

alias dcrestart='dcdown && dcup'

function dcx {
  if is_shipper_version_tag_set; then
    docker-compose exec "$@"
  fi
}

alias dcd='docker-compose -f docker-compose.dev.yml'
alias dcdup='docker-compose -f docker-compose.dev.yml up -d --build'
alias dcddown='docker-compose -f docker-compose.dev.yml down'
alias dcdrestart='dcddown && dcdup'
alias dcdx='docker-compose -f docker-compose.dev.yml exec'
alias dcdsetup='./django-update.sh'

function setversion {
  export VERSION_TAG=$1
}

function setlatest {
    export VERSION_TAG=$(curl https://api.github.com/repos/shipperstack/shipper/releases/latest | python -c "import sys, json; print json.load(sys.stdin)['name']")
    echo "GitHub: latest version available is $VERSION_TAG"
}

echo "Finished loading commands for shipper-docker. Run helpme for usage."