# v6

version: "3.8"

services:
  web:
    image: ghcr.io/shipperstack/shipper-docker/shipper:${VERSION_TAG}
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --capture-output --timeout 360 --log-level debug
    volumes:
    - media_volume:/home/shipper/web/media
    - static_volume:/home/shipper/web/static
    - ./ssh/:/home/shipper/ssh
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15.2-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.db
  nginx:
    image: nginx:latest
    volumes:
    - ./nginx/:/etc/nginx/conf.d
    - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    - media_volume:/home/shipper/web/media
    - static_volume:/home/shipper/web/static
    ports:
      - "9200:80"
      - "9201:81"
    healthcheck:
      test: curl --fail http://localhost/api/v1/system/info/ || exit 1
    depends_on:
      - web
      - flower
  celery:
    restart: unless-stopped
    image: ghcr.io/shipperstack/shipper-docker/shipper:${VERSION_TAG}
    command: celery -A core worker -l info
    volumes:
      - media_volume:/home/shipper/web/media
      - ./ssh/:/home/shipper/ssh
    env_file:
      - ./.env
    depends_on:
      - db
      - rabbitmq
      - web
  celery_beat:
    restart: unless-stopped
    image: ghcr.io/shipperstack/shipper-docker/shipper:${VERSION_TAG}
    command: celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - media_volume:/home/shipper/web/media
      - ./ssh/:/home/shipper/ssh
    env_file:
      - ./.env
    depends_on:
      - db
      - rabbitmq
      - web
  rabbitmq:
    image: rabbitmq:3.8.16-alpine
  flower:
    image: mher/flower:latest
    command: celery --broker=pyamqp://rabbitmq:5672/ flower --port=5555 --purge_offline_workers=5
    depends_on:
      - rabbitmq

volumes:
  postgres_data:
    name: shipper_postgres_data
  media_volume:
    name: shipper_media_volume
  static_volume:
    name: shipper_static_volume
